#!/bin/bash
set -e

if systemctl is-active --quiet stretcher.service; then
    systemctl stop stretcher.service
fi

if systemctl is-enabled --quiet stretcher.service; then
    systemctl disable stretcher.service
fi

exit 0
