name: CI
on:
  push:
    branches: main
    tags: v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:   [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Get version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}
          else
            PACKAGE_VERSION="1.0.0"
          fi
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Cross-compile
        env:
          CGO_ENABLED: 0
          GOOS:   ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          ext=$([[ "$GOOS" == windows ]] && echo .exe) || true
          mkdir -p artifacts
          go build -trimpath -ldflags "-s -w -X main.Version=$PACKAGE_VERSION" -o artifacts/stretcher-${GOOS}-${GOARCH}${ext} stretcher.go

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-build-${{ matrix.goos }}-${{ matrix.goarch }}
          path: artifacts/*
          if-no-files-found: error

  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Get version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}
          else
            PACKAGE_VERSION="1.0.0"
          fi
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Build Debian package
        run: |
          mkdir -p debian/usr/bin artifacts
          sed -i "s/^Version:.*/Version: $PACKAGE_VERSION/" debian/DEBIAN/control
          go build -trimpath -ldflags "-s -w -X main.Version=$PACKAGE_VERSION" -o debian/usr/bin/stretcher stretcher.go
          chmod 755 debian/DEBIAN/postinst debian/DEBIAN/prerm debian/DEBIAN/postrm debian/usr/bin/stretcher
          dpkg-deb --build debian artifacts/stretcher_linux_amd64.deb

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-build-deb
          path: artifacts/*
          if-no-files-found: error

  release:
    needs: [build, build-deb]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          merge-multiple: true
          path: release

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: release/*
